version: "3.8"

services:
  app:
    container_name: snippets
    image: snippets
    build:
      context: .
      target: deployment
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

